---
name: DNSControl Action with fetch functionality
description: Deploy your DNS configuration to multiple providers
author: Jniklas2 <github@sl.crcr.tech>
branding:
  icon: cloud
  color: yellow
inputs:
  args:
    description: DNSControl command
    required: true
  config_file:
    description: Path to DNSControl configuration file.
    required: false
    default: 'dnsconfig.js'
  creds_file:
    description: Path to DNSControl credentials file.
    required: false
    default: 'creds.json'
  enable_colors:
    description: Enable colors in the output.
    required: false
    default: 'false'
  allow_fetch:
    description: Enable the fetch function.
    required: false
    default: 'false'
  disable_ordered_update:
    description: Disable the ordered update function.
    required: false
    default: 'false'
  enable_concurrent:
    description: Enable concurrent execution of commands.
    required: false
    default: 'true'
outputs:
  output:
    description: The output of the dnscontrol command that was executed.
runs:
  using: docker
  image: 'Dockerfile'
